name: testing-actions
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository code
      - uses: actions/checkout@v2
      # Configure python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Download App Engine SDK
      - uses: google-github-actions/setup-gcloud@v0
      # Update the App Engine environment
      - run: gcloud -q components update
      - run: gcloud -q components install app-engine-python
      # Setup the CRMint test environment
      - run: pip install -r backend/requirements-controller.txt
      - run: pip install -r backend/requirements-jobs.txt
      - run: pip install -r backend/tests/requirements.txt
      # Run the tests
      - run: cd backend && python runtests.py
      - run: cd cli && python runtests.py
